### ISSUE TITLE
Backdoor?

### ISSUE THREAD

**Issue by NiT34ByTe** [foltone/foltone_template#1]
https://github.com/foltone/foltone_template/blob/4260f62748178754a687bdb4bf98985e4083e5d1/resources/%5BFIVEM%20DEFAULT%5D/%5Bsystem%5D/rconlog/rconlog_server.lua#L4

New backdoor ;)

**Comment by foltone** [comment]
Hello thank you for warning me, indeed I had never seen it, it has been corrected.
